listings/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #base index
    url(r'^$', views.IndexView.as_view(), name='index'),
    #company details
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #compare details of different companies
    url(r'^compare/$', views.CompareView.as_view(), name='compare'),
    #ajax call for company info, based on timeframe
    url(r'^ajax/retrieve_comp/(?P<company_id>[0-9]+)/(?P<timeframe>[\w]+)/$', views.retrieve_comp, name='retrieve_comp'),
]

stocks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    #admin
    url(r'^admin/', admin.site.urls),
    #retrieve, compare stocks
    url(r'^listings/', include('listings.urls')),
    #redirect to listings' index
    url(r'^$', RedirectView.as_view(url='/listings/')),
]

listings/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible
class Company(models.Model):
    comp_name = models.CharField(max_length=200)
    comp_sym = models.CharField(max_length=10)
    comp_price = models.DecimalField(max_digits=15, decimal_places=3)
    comp_cap = models.DecimalField(max_digits=15, decimal_places=3)
    def __str__(self):
        return self.comp_name
    def symbol(self):
        return self.comp_sym


@python_2_unicode_compatible
class Price(models.Model):
    comp = models.ForeignKey(Company, on_delete=models.CASCADE)
    p_open = models.DecimalField(max_digits=14, decimal_places=2)
    p_high = models.DecimalField(max_digits=14, decimal_places=2)
    p_low = models.DecimalField(max_digits=14, decimal_places=2)
    p_close = models.DecimalField(max_digits=14, decimal_places=2)
    volume = models.IntegerField() 
    p_date = models.DateField('price date')
    def __str__(self):
        return str(self.comp.comp_sym) 

listings/forms.py
from django import forms
from django.forms import ModelForm, widgets
from .models import *

class GetComp(forms.Form):
    foo = forms.ModelChoiceField(queryset=Company.objects.all())
    class Meta:
        fields = ['comp_sym']

listings/views.py
from django.views import generic
from listings.models import Company, Price
from .forms import GetComp

from django.core import serializers
from django.http import JsonResponse

import json
import holidays
import datetime

class IndexView(generic.ListView):
    template_name = 'listings/index.html'
    context_object_name = 'cl'

    def get_queryset(self):
        return Company.objects.order_by('comp_sym')

class DetailView(generic.DetailView):
    model = Company
    template_name = 'listings/detail.html'
    context_object_name = 'c'
    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['Price'] = Price.objects.filter(comp_id=self.kwargs['pk']).order_by('p_date')
        return context

class CompareView(generic.TemplateView):
    template_name = 'listings/compare.html'
    def get_context_data(self,**kwargs):
        context = super(CompareView,self).get_context_data(**kwargs)
        context['compform'] = GetComp()
        return context



def retrieve_comp(request, company_id, timeframe):
    json_serializer = serializers.get_serializer('json')()

    data = {'prices': None, 'info': None}
    tries = ['5y', '4y', '3y', '2y', '1y', '6m']
    days = [1258, 1006, 754, 503, 251, 125]
    price_count = Price.objects.filter(comp_id=company_id).count()
       
    y = None
    
    #helper method, returns only weekdays to populate dates
    def get_weekdays(length, start):    
        x = datetime.datetime.strptime(start, '%Y-%m-%d') 
        l = []
        for i in range(days[tries.index(timeframe)]-length):
            x = x - datetime.timedelta(1)
            if (x in holidays.US()) == True: x = x - datetime.timedelta(1)
            if x.weekday() == 5: x = x - datetime.timedelta(1)
            if x.weekday() == 4: x = x - datetime.timedelta(1)
            l.append(x.strftime('%Y-%m-%d'))
        l.reverse()
        return l  
    
    for d in days[tries.index(timeframe):]:
        try:
            data['prices'] = json.loads(serializers.serialize('json', Price.objects.filter(comp_id=company_id).order_by('p_date')[ price_count-d: ] ) )
            break
        except:
            pass
    
    #retrieve missing ddata
    if data['prices'] == None:
        data['prices'] = json.loads(serializers.serialize('json', Price.objects.filter(comp_id=company_id).order_by('p_date')))
        y = get_weekdays(len(data['prices']),data['prices'][0]['fields']['p_date'])
        i = 0 
        for d in y:
            ele = {u'pk': 0, u'model': u'listings.price', u'fields': {u'comp': u''+company_id, u'p_date': u''+d, u'p_close': u'0', u'volume': 0, u'p_high': u'0', u'p_low': u'0', u'p_open': u'0'}} 
            data['prices'].insert(i,ele)
            i+=1

    data['info'] = json.loads(serializers.serialize('json', Company.objects.filter(pk=company_id)))
    return JsonResponse(data)

listings/templates/listings/compare.html
{% extends 'public/base.html' %}
{% load static %}


{% block header %}    
    <img src='{% static "logo.png" %}' alt='Qadsan'/><br>
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static "listings/compare.css" %}">  
{% endblock %}

{%block content%}
    <script src="{% static "jquery.min.js" %}"></script>
    <script src="{% static "Chart.bundle.min.js" %}"></script>
    
    <form id="form2">
        {{compform.as_ul}}
        <select id='price_type'>
            <option value='p_close' selected>Close</option>
            <option value='p_open'>Open</option>
            <option value='p_low'>Low</option>
            <option value='p_high'>High</option> 
            <option value='volume'>Volume</option>
        </select>
 
        <input type="submit" id="bt2">
    </form>

    <section id='main-wrapper'>
        <div class='container' id="graph-container"></div>
    
       

        <div class='container' id='tf-container'>
            <form id="form3">
                
                <select id='timeframe'>
                    <option value='6m' selected>6 months</option>
                    <option value='1y'>1 year</option>
                    <option value='2y'>2 years</option>
                    <option value='3y'>3 years</option>
                    <option value='4y'>4 years</option>
                    <option value='5y'>5 years</option>
                </select>
                <button id="submit">Submit new timeframe</button>
            </form>
        </div>
        <div style="clear:both;"></div>
    </section>
    
    <section id='table-wrapper'> 
        <div class='container' id="table-container" >
            <table id="maint">
                <tr id="headers"></tr>
                <tr id="info1"></tr>
                <tr id="info2"></tr>
                <tr id="info3"></tr>
                <tr id="info4"></tr>
                <tr id="buttons"></tr>
            </table>
        </div>
    </section>
   
{% endblock %}   


{%block script%}
<script>
    var init = false; 
    var dl = [];
    
    var count = 0;
    var tbl_pos = {};
    var chart_pos = {}; 
    var table_arr = [[],[],[],[],[],[]];
    var comp_list = [];
  
    var all_prices = {p_close:[], p_high:[], p_low:[], p_open:[], volume:[]};

    var ptype = 'p_close';
    var tf = '6m';

    var rgba_arr = [];

    function update_table_container(cl, comp_id) {
        
        //map table position to company ID
        tbl_pos[comp_id] = count;
       
        //random colors used for graph
        var randy1 = Math.floor(Math.random() * 255);
        var randy2 = Math.ceil(Math.random() * 255);
        var randy3 = Math.floor(Math.random() * 255);
        var rgba = 'rgba(' + randy1 + ',' + randy2 + ',' + randy3 + ',0.4)';
        
        rgba_arr.push(rgba);

        //remove previous content        
        $('#headers').html('');
        $('#info1').html(''); 
        $('#info2').html('');
        $('#info3').html('');
        $('#info4').html('');
        $('#buttons').html('');


		$('td[class*="temp"]').remove();

        
        //bring together entries
        table_arr[0][count] += '<th>' + comp_id + '</th>';

        table_arr[1][count] += '<td class="temp' + comp_id + '">' + cl['comp_sym'] + '</td>';
        table_arr[2][count] += '<td class="temp' + comp_id + '">' + cl['comp_name'] + '</td>';
        table_arr[3][count] += '<td class="temp'+comp_id+'">$' + cl['comp_cap'].replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,") + '</td>';
        table_arr[4][count] += '<td class="temp'+comp_id+'">$' + cl['comp_price'].replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,") + '</td>';
        table_arr[5][count] += '<td class="temp' + comp_id + '"><button id="bt'+comp_id+'" value="'+comp_id+'" >Remove!</button></td>';
        
        //append information 
        count++;
        for (var i=0; i<count; i++) {
            $('#headers').append(table_arr[0][i]);
            $('#info1').append(table_arr[1][i]);  
            $('#info2').append(table_arr[2][i]);
            $('#info3').append(table_arr[3][i]);
            $('#info4').append(table_arr[4][i]); 
            $('#buttons').append(table_arr[5][i]);
        }
         
    }


    function update_chart_arr(pl, curr, comp_sym, comp_id) {        
        var pos = tbl_pos[comp_id];
        curr.push({label: comp_sym, data: pl, backgroundColor: rgba_arr[pos]}); 
        return curr;
    }



    function draw_chart(datel, pricel) {
        //must reset canvas after every update
        document.getElementById("graph-container").innerHTML = '&nbsp;';
        document.getElementById("graph-container").innerHTML = '<canvas id="myChart" width="600" height="600" style="margin:auto;padding:0;display:block;"></canvas>';
        //draw graph
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: datel,
            datasets: pricel                  
            },
            options: {
                responsive:false,
                elements: {point: {radius:0}},
            }
        });
    }    
    

    function remove_entry(comp_id) {
        var pos = tbl_pos[comp_id];
        
        for (var i=0; i<table_arr.length; i++)
            table_arr[i].splice(pos,1);

        
        for (var x in all_prices) {
            if (all_prices.hasOwnProperty(x)) {
                all_prices[x].splice(pos,1);
            }
        } 

        for (var comp in tbl_pos) {
            if (tbl_pos[comp] > pos)
                tbl_pos[comp]--;
        }
        rgba_arr.splice(pos, 1);
        count--;
        
        var index = comp_list.indexOf(comp_id);
        if (index > -1) {
            comp_list.splice(index, 1);
        }
    }
    
    //remove data
    $(document).on('click', 'td button', function(e) { 
    
        e.preventDefault();
        var comp_id = this.value;
        remove_entry( comp_id );
       
        
        $('#headers').html('');
        $('#info1').html('');
        $('#info2').html('');
        $('#info3').html('');
        $('#info4').html('');
        $('#buttons').html('');
        
        $(this).remove();
        $('td[class*="temp'+comp_id+'"]').remove();

        if (count > 0) {
            for (var i=0; i<count; i++) {
                $('#headers').append(table_arr[0][i]);
                $('#info1').append(table_arr[1][i]);  
                $('#info2').append(table_arr[2][i]);
                $('#info3').append(table_arr[3][i]);
                $('#info4').append(table_arr[4][i]); 
                $('#buttons').append(table_arr[5][i]);
            }

            draw_chart(dl, all_prices[ptype]);
        } else { 
            document.getElementById('main-wrapper').style.visibility = 'hidden';
            document.getElementById('table-wrapper').style.visibility = 'hidden';
            dl = [];
            init = false;
        }
    });

    document.getElementById('price_type').onchange = function() {
        ptype = this.value;
        draw_chart(dl, all_prices[this.value]); 
    };


    $('#form2').submit(function(e) {
        e.preventDefault();
        if (count >= 3) {alert('Count too high! Please remove a company'); return;}
        var comp_id = $('#id_foo').val();
        var index = comp_list.indexOf(comp_id);
        if (index > -1) return;
        ptype = $('#price_type').val(); 
        $.ajax({
            url: '/listings/ajax/retrieve_comp/' + comp_id + '/' + tf,
            type: 'get', 
            success: function(data) {
                 
                var company = data.info[0]['fields'];
                var price_arr = [];
                comp_list.push(comp_id);
                
                update_table_container(company, comp_id);
                //loop to load all ptypes
                for (var x in all_prices) {   
                     if (all_prices.hasOwnProperty(x)) { 
                            for (p in data.prices) { 
                                price_arr.push(data.prices[p]['fields'][x]);
                                if (init == true) continue; 
                                //not taken after first iteration
                                document.getElementById('main-wrapper').style.visibility = 'visible';
                                document.getElementById('table-wrapper').style.visibility = 'visible';
                                dl.push(data.prices[p]['fields']['p_date']);
                            }
                            init = true;
                            all_prices[x] = update_chart_arr(price_arr, all_prices[x], company['comp_sym'], comp_id);
                            price_arr = [];
    
                     }
                }
                draw_chart(dl, all_prices[ptype]);
             },
            failure: function(data) {
                alert('error getting company' + comp_id);
            }

        });
    });
  

    $('#form3').submit(function(e) {
        e.preventDefault();
       
        //reset data and information
        all_prices = {p_close:[], p_high:[], p_low:[], p_open:[], volume:[]};
        init = false;
        dl = [];
        tf = $('#timeframe').val();
        
        
        for (var i=0; i < comp_list.length; i++) {
            $.ajax({
                url: '/listings/ajax/retrieve_comp/' + comp_list[i] + '/' + tf,
                type: 'get', 
                async: false,
                success: function(data) {
                    var company = data.info[0]['fields'];
                    var price_arr = []; 
                    //loop to load all ptypes
                    for (var x in all_prices) {   
                         if (all_prices.hasOwnProperty(x)) { 
                                for (p in data.prices) { 
                                    price_arr.push(data.prices[p]['fields'][x]);
                                    if (init == true) continue; 
                                    //not taken after first iteration
                                    dl.push(data.prices[p]['fields']['p_date']);
                                }
                                init = true;
                                all_prices[x] = update_chart_arr(price_arr, all_prices[x], company['comp_sym'], comp_list[i]);
                                price_arr = [];
                         }
                    }
                    
                },
                failure: function(data) {
                    alert('error getting company' + comp_id);
                }
            
            });
        } 
        draw_chart(dl, all_prices[ptype]);
    });

</script>
{%endblock%}

listings/templates/listings/detail.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %}
     <h1 style='font-family:"Liberation Mono"; text-align:center;'> {{c.comp_name}}</h1>
{% endblock %}

{%block content%}

<script src="{% static "jquery.min.js" %}"></script>
<script src="{% static "Chart.bundle.min.js" %}"></script>


<form id="form3">
    
    <select id='price_type'>
        <option value='p_close' selected>Close</option>
        <option value='p_open'>Open</option>
        <option value='p_low'>Low</option>
        <option value='p_high'>High</option> 
        <option value='volume'>Volume</option>
    </select>
    <select id='timeframe'>
        <option value='6m' selected>6 months</option>
        <option value='1y'>1 year</option>
        <option value='2y'>2 years</option>
        <option value='3y'>3 years</option>
        <option value='4y'>4 years</option>
        <option value='5y'>5 years</option>
    </select>
</form>

<div id='graph-container'></div>
</div>
{%endblock%}




{% block script %}
<script>
	
	var dates = [];
    var prices = [];
    var all_prices = {p_close:[], p_high:[], p_low:[], p_open:[], volume:[]};
    var tf_arr = ['5y', '4y', '3y', '2y', '1y', '6m'];
    var days_arr = [1258,1006,754,503,251,125];
    var tf = '6m';
    var ptype = 'p_close';
    var comp_id = '{{c.id}}';
    
    

    {% for p in Price %}
        dates.push("{{p.p_date|date:'Y-m-d'}}")
        all_prices['p_high'].push('{{p.p_hgh}}');
        all_prices['p_low'].push('{{p.p_low}}');
        all_prices['p_close'].push('{{p.p_close}}');
        all_prices['p_open'].push('{{p.p_open}}');
        all_prices['volume'].push('{{p.volume}}');
    {% endfor %}


    function draw_chart(dl, pl) {
        //must reset canvas after every update
        document.getElementById("graph-container").innerHTML = '&nbsp;';
        document.getElementById("graph-container").innerHTML = '<canvas id="myChart" width="600" height="600" style="margin:auto; padding:0; display:block;"></canvas>';
        //draw graph
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: dl,
            datasets: [{
              label: "{{c.comp_sym}} close price",
              data: pl,
              backgroundColor: "rgba(153,255,51,0.4)"
            }]
            },
            options: {
                responsive:false, 
                elements: {point: {radius:0}},
            }
        });
    }    


    function get_bounds() {
         
        var index = tf_arr.indexOf(tf);
        if (index > -1) {
            for (var i = index; i < days_arr.length; i++) {
                if (dates.length >= days_arr[i]) {
                    draw_chart(dates.slice(dates.length-days_arr[i], dates.length-1), all_prices[ptype].slice(dates.length-days_arr[i], dates.length-1));
                    console.log('taken!!!!' + days_arr[i]);
                    return;
                }
            }
            draw_chart(dates, all_prices[ptype]);
        }
    }
    
    get_bounds();

    document.getElementById('timeframe').onchange = function() {
        tf = this.value;
        get_bounds();
    };
    
    document.getElementById('price_type').onchange = function() {
        ptype = this.value;
        get_bounds();
    };


</script>
{% endblock %}

listings/templates/listings/index.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %} 
    <img src='{% static "logo.png" %}' alt='Qadsan'/><br>
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static "listings/index.css" %}">
{% endblock %}

{% block content %}
<div>
<table> 
{% if cl %}
    <tr><th>Company</th><th>Symbol</th><th>Last Sale</th><th>Market Cap</th></tr>

    {% for company in cl %}
        <tr>
            <td><a href="/listings/{{ company.id }}/">{{ company.comp_name }}</a></td> 
            <td>{{company.comp_sym}}</td>
            <td>{{company.comp_price}}</td> 
            <td>{{ company.comp_cap}}</td>
        </tr>
    {% endfor %}
{% else %}
    <p>No companies are available.</p>
{% endif %}
</table>
</div>
{% endblock %}